const SERVER_API_ENDPOINT = import.meta.env.VITE_SERVER_BACKEND_ENDPOINT || 'l';
const API_KEY = import.meta.env.VITE_API_KEY || '';
const REQUEST_TIMEOUT = Number(
  import.meta.env.VITE_REQUEST_TIMEOUT || 8 * 1000
);

const DEFAULT_LIMIT = 8;
const DEFAULT_MIN_PRICE = 0;
const DEFAULT_MAX_PRICE = 1000000;
const DEFAULT_PAGE = 1;
const DEFAULT_CATEGORY_ID = 'ALL';

export {
  SERVER_API_ENDPOINT,
  API_KEY,
  REQUEST_TIMEOUT,
  DEFAULT_LIMIT,
  DEFAULT_MIN_PRICE,
  DEFAULT_MAX_PRICE,
  DEFAULT_PAGE,
  DEFAULT_CATEGORY_ID,
};
