export enum EnumRole {
  ADMIN = 'ADMIN',
  USER = 'USER',
  GUEST = 'GUEST',
  'SHIPPER' = 'SHIPPER',
  'EMPLOYEE' = 'EMPLOYEE',
}

export interface InterfaceAuthInformationMetaData {
  user: {
    userId: string;
    name: string;
    email: string;
    role_list: string[];
    address: string;
    avatar_url: string;
    phone_number: string;
    status: boolean;
    verified: boolean;
  };
  tokens: {
    accessToken: string;
    refreshToken: string;
  };
  roleList: Array<string>;
}

export interface InterfaceErrorResponse {
  statusCode: number;
  message: string;
  reasonStatusCode: EnumReasonStatusCode;
  status: string;
  stack: string;
}

export enum EnumReasonStatusCode {
  INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  INVALID_USER_ID = 'INVALID_USER_ID',
  NOT_HAVE_ACCESS_TOKEN = 'NOT_HAVE_ACCESS_TOKEN',
  NOT_HAVE_PERMISSION = 'NOT_HAVE_PERMISSION',
  EXPIRED_ACCESS_TOKEN = 'EXPIRED_ACCESS_TOKEN',
  EXPIRED_REFRESH_TOKEN = 'EXPIRED_REFRESH_TOKEN',
  REFRESH_TOKEN_SUCCESSFULLY = 'REFRESH_TOKEN_SUCCESSFULLY',
  FORBIDDEN_PERMISSION = 'FORBIDDEN_PERMISSION',
  SUCCESS = 'SUCCESS',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND_USER = 'NOT_FOUND_USER',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND_USER_ID = 'NOT_FOUND_USER_ID',
  NOT_FOUND_CLIENT = 'NOT_FOUND_CLIENT',
  NOT_FOUND_ACCESS_TOKEN = 'NOT_FOUND_ACCESS_TOKEN',
  NOT_FOUND_REFRESH_TOKEN = 'NOT_FOUND_REFRESH_TOKEN',
  REFRESH_TOKEN_USED = 'REFRESH_TOKEN_USED',
  CREATE_TOKEN_PAIR_FAILED = 'CREATE_TOKEN_PAIR_FAILED',
  INVALID_CLIENT_ID = 'INVALID_CLIENT_ID',
  EXPIRED_API_KEY = 'EXPIRED_API_KEY',
  INVALID_API_KEY = 'INVALID_API_KEY',
  NOT_FOUND_API_KEY = 'NOT_FOUND_API_KEY',
  NOT_FOUND_PRODUCT = 'NOT_FOUND_PRODUCT',
  NOT_FOUND_CATEGORY = 'NOT_FOUND_CATEGORY',
  NOT_FOUND_ORDER = 'NOT_FOUND_ORDER',
  NOT_FOUND_ORDER_DETAIL = 'NOT_FOUND_ORDER_DETAIL',
  NOT_FOUND_COMMENT = 'NOT_FOUND_COMMENT',
  NOT_FOUND_USER_ADDRESS = 'NOT_FOUND_USER_ADDRESS',
  NOT_FOUND_USER_PAYMENT = 'NOT_FOUND_USER_PAYMENT',
  NOT_FOUND_USER_SHIPPING = 'NOT_FOUND_USER_SHIPPING',
  NOT_FOUND_USER_WISHLIST = 'NOT_FOUND_USER_WISHLIST',
  NOT_FOUND_USER_CART = 'NOT_FOUND_USER_CART',
  NOT_FOUND_USER_ORDER = 'NOT_FOUND_USER_ORDER',
  NOT_FOUND_USER_ORDER_DETAIL = 'NOT_FOUND_USER_ORDER_DETAIL',
  NOT_FOUND_USER_WISHLIST_PRODUCT = 'NOT_FOUND_USER_WISHLIST_PRODUCT',
  NOT_FOUND_USER_CART_PRODUCT = 'NOT_FOUND_USER_CART_PRODUCT',
  NOT_FOUND_USER_ADDRESS_SHIPPING = 'NOT_FOUND_USER_ADDRESS_SHIPPING',
  NOT_FOUND_USER_ADDRESS_BILLING = 'NOT_FOUND_USER_ADDRESS_BILLING',
  NOT_FOUND_USER_ADDRESS_BILLING_SAME = 'NOT_FOUND_USER_ADDRESS_BILLING_SAME',
  NOT_FOUND_USER_ADDRESS_BILLING_ORDER = 'NOT_FOUND_USER_ADDRESS_BILLING_ORDER',
  NOT_FOUND_USER_PAYMENT_ORDER = 'NOT_FOUND_USER_PAYMENT_ORDER',
  NOT_FOUND_USER_PAYMENT_ORDER_SAME = 'NOT_FOUND_USER_PAYMENT_ORDER_SAME',
  NOT_FOUND_USER_PAYMENT_ORDER_BILLING = 'NOT_FOUND_USER_PAYMENT_ORDER_BILLING',
  NOT_FOUND_USER_PAYMENT_ORDER_BILLING_SAME = 'NOT_FOUND_USER_PAYMENT_ORDER_BILLING_SAME',
  NOT_FOUND_USER_PAYMENT_ORDER_BILLING_ORDER = 'NOT_FOUND_USER_PAYMENT_ORDER_BILLING_ORDER',
  NOT_FOUND_USER_PAYMENT_ORDER_BILLING_ORDER_SAME = 'NOT_FOUND_USER_PAYMENT_ORDER_BILLING_ORDER_SAME',
  NOT_FOUND_USER_PAYMENT_ORDER_BILLING_ORDER_SAME_SAME = 'NOT_FOUND_USER_PAYMENT_ORDER_BILLING_ORDER_SAME_SAME',
  NOT_FOUND_USER_PAYMENT_ORDER_BILLING_ORDER_SAME_SAME_SAME = 'NOT_FOUND_USER_PAYMENT_ORDER_BILLING_ORDER_SAME_SAME_SAME',
  NOT_FOUND_USER_SHIPPING_ORDER = 'NOT_FOUND_USER_SHIPPING_ORDER',
  SIGN_UP_SUCCESSFULLY = 'SIGN_UP_SUCCESSFULLY',
  CREATE_KEY_TOKEN_FAILED = 'CREATE_KEY_TOKEN_FAILED',
  EXISTED_USER = 'EXISTED_USER',
  LOGOUT_SUCCESSFULLY = 'LOGOUT_SUCCESSFULLY',
  LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  CREATED_SUCCESSFULLY = 'CREATED_SUCCESSFULLY',
}
